services:
  primary-mongodb: 
    extends:
      file: docker-compose-mongodb-replSet.yaml
      service: primary-db
    networks:
      - testing-network
    container_name: primary-test-db
    ports:
      - 27011:27017

  secondary-mongodb-1: 
    extends:
      file: docker-compose-mongodb-replSet.yaml
      service: secondary-db-1
    networks:
      - testing-network
    container_name: secondary-test-db-1
    ports:
      - 27012:27017

  secondary-mongodb-2: 
    extends:
      file: docker-compose-mongodb-replSet.yaml
      service: secondary-db-2
    networks:
      - testing-network
    container_name: secondary-test-db-2
    ports:
      - 27013:27017

networks:
  testing-network: 
    driver: bridge