services:
  server:
    image: localhost:5000/llms-tdm-server:stage
    command: bun start
    env_file:
      - .env.staging
    networks:
      - staging-network
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
        delay: 10s
      update_config:
        parallelism: 1
        delay: 5s
      resources:
        limits:
          cpus: '0.7'
          memory: 275mb

  nginx:
    image: localhost:5000/nginx:stable
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - server
    ports:
      - 80:80
    networks:
      - staging-network
    deploy: 
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
      update_config:
        parallelism: 1
      resources:
        limits:
          cpus: '0.3'
          memory: 165mb

networks:
  staging-network:
    external: true
    name: staging-network