services:
  ## Router
  router1:
    build:
      context: mongodb
    image: mongodb:v8
    container_name: db-router1
    command: mongos --config /etc/mongos.conf
    volumes:
      - ./mongodb/configs/mongos.conf:/etc/mongos.conf:ro
      - ./mongodb/scripts/addShardsToRouter.js:/scripts/addShardsToRouter.js:ro
      - ./mongodb/scripts/shardingSettingUp.js:/scripts/shardingSettingUp.js:ro
      - mongodb_cluster_router1_db:/data/db
      - mongodb_cluster_router1_config:/data/configdb
    ports:
      - 27117:27017
    restart: always
    networks:
      - ${ENVIRONMENT_NETWORK}
    mem_limit: 200mb

  router2:
    build:
      context: mongodb
    image: mongodb:v8
    container_name: db-router2
    command: mongos --config /etc/mongos.conf
    volumes:
      - ./mongodb/configs/mongos.conf:/etc/mongos.conf:ro
      - mongodb_cluster_router2_db:/data/db
      - mongodb_cluster_router2_config:/data/configdb
    ports:
      - 27118:27017
    restart: always
    links:
      - router1
    networks:
      - ${ENVIRONMENT_NETWORK}
    mem_limit: 200mb

  ## Config Servers
  configsvr1:
    build:
      context: mongodb
    image: mongodb:v8
    container_name: config-server1
    command: mongod --config /etc/mongod.conf
    volumes:
      - ./mongodb/configs/configsvr.conf:/etc/mongod.conf:ro
      - ./mongodb/configs/configsvrReplSet.js:/configs/configsvrReplSet.js:ro
      - ./mongodb/scripts/initializingReplSetScript.js:/scripts/initializingReplSetScript.js:ro
      - ./mongodb/scripts/createRootAdmin.js:/scripts/createRootAdmin.js:ro
      - mongodb_cluster_configsvr1_db:/data/db
      - mongodb_cluster_configsvr1_config:/data/configdb
    ports:
      - 27119:27017
    restart: always
    links:
      - shard1-a
      - shard2-a
      - shard3-a
      - configsvr2
      - configsvr3
    networks:
      - ${ENVIRONMENT_NETWORK}
    mem_limit: 200mb

  configsvr2:
    build:
      context: mongodb
    image: mongodb:v8
    container_name: config-server2
    command: mongod --config /etc/mongod.conf
    volumes:
      - ./mongodb/configs/configsvr.conf:/etc/mongod.conf:ro
      - mongodb_cluster_configsvr2_db:/data/db
      - mongodb_cluster_configsvr2_config:/data/configdb
    ports:
      - 27120:27017
    restart: always
    networks:
      - ${ENVIRONMENT_NETWORK}
    mem_limit: 200mb

  configsvr3:
    build:
      context: mongodb
    image: mongodb:v8
    container_name: config-server3
    command: mongod --config /etc/mongod.conf
    volumes:
      - ./mongodb/configs/configsvr.conf:/etc/mongod.conf:ro
      - mongodb_cluster_configsvr3_db:/data/db
      - mongodb_cluster_configsvr3_config:/data/configdb
    ports:
      - 27121:27017
    restart: always
    networks:
      - ${ENVIRONMENT_NETWORK}
    mem_limit: 200mb

  ## Shards 1
  shard1-a:
    build:
      context: mongodb
    image: mongodb:v8
    container_name: shard1-node-a
    command: mongod --config /etc/mongod.conf --replSet shard1-rs
    volumes:
      - ./mongodb/configs/shardsvr.conf:/etc/mongod.conf:ro
      - ./mongodb/configs/shard1ReplSet.js:/configs/shard1ReplSet.js:ro
      - ./mongodb/scripts/initializingReplSetScript.js:/scripts/initializingReplSetScript.js:ro
      - ./mongodb/scripts/createRootAdmin.js:/scripts/createRootAdmin.js:ro
      - mongodb_cluster_shard1_a_db:/data/db
      - mongodb_cluster_shard1_a_config:/data/configdb
    ports:
      - 27122:27017
    restart: always
    links:
      - shard1-b
      - shard1-c
    networks:
      - ${ENVIRONMENT_NETWORK}
    mem_limit: 200mb

  shard1-b:
    build:
      context: mongodb
    image: mongodb:v8
    container_name: shard1-node-b
    command: mongod --config /etc/mongod.conf --replSet shard1-rs
    volumes:
      - ./mongodb/configs/shardsvr.conf:/etc/mongod.conf:ro
      - mongodb_cluster_shard1_b_db:/data/db
      - mongodb_cluster_shard1_b_config:/data/configdb
    ports:
      - 27123:27017
    restart: always
    networks:
      - ${ENVIRONMENT_NETWORK}
    mem_limit: 200mb

  shard1-c:
    build:
      context: mongodb
    image: mongodb:v8
    container_name: shard1-node-c
    command: mongod --config /etc/mongod.conf --replSet shard1-rs
    volumes:
      - ./mongodb/configs/shardsvr.conf:/etc/mongod.conf:ro
      - mongodb_cluster_shard1_c_db:/data/db
      - mongodb_cluster_shard1_c_config:/data/configdb
    ports:
      - 27124:27017
    restart: always
    networks:
      - ${ENVIRONMENT_NETWORK}
    mem_limit: 200mb

  ## Shards 2
  shard2-a:
    build:
      context: mongodb
    image: mongodb:v8
    container_name: shard2-node-a
    command: mongod --config /etc/mongod.conf --replSet shard2-rs
    volumes:
      - ./mongodb/configs/shardsvr.conf:/etc/mongod.conf:ro
      - ./mongodb/configs/shard2ReplSet.js:/configs/shard2ReplSet.js:ro
      - ./mongodb/scripts/initializingReplSetScript.js:/scripts/initializingReplSetScript.js:ro
      - ./mongodb/scripts/createRootAdmin.js:/scripts/createRootAdmin.js:ro
      - mongodb_cluster_shard2_a_db:/data/db
      - mongodb_cluster_shard2_a_config:/data/configdb
    ports:
      - 27125:27017
    restart: always
    links:
      - shard2-b
      - shard2-c
    networks:
      - ${ENVIRONMENT_NETWORK}
    mem_limit: 200mb

  shard2-b:
    build:
      context: mongodb
    image: mongodb:v8
    container_name: shard2-node-b
    command: mongod --config /etc/mongod.conf --replSet shard2-rs
    volumes:
      - ./mongodb/configs/shardsvr.conf:/etc/mongod.conf:ro
      - mongodb_cluster_shard2_b_db:/data/db
      - mongodb_cluster_shard2_b_config:/data/configdb
    ports:
      - 27126:27017
    restart: always
    networks:
      - ${ENVIRONMENT_NETWORK}
    mem_limit: 200mb

  shard2-c:
    build:
      context: mongodb
    image: mongodb:v8
    container_name: shard2-node-c
    command: mongod --config /etc/mongod.conf --replSet shard2-rs
    volumes:
      - ./mongodb/configs/shardsvr.conf:/etc/mongod.conf:ro
      - mongodb_cluster_shard2_c_db:/data/db
      - mongodb_cluster_shard2_c_config:/data/configdb
    ports:
      - 27127:27017
    restart: always
    networks:
      - ${ENVIRONMENT_NETWORK}
    mem_limit: 200mb

  ## Shards 3
  shard3-a:
    build:
      context: mongodb
    image: mongodb:v8
    container_name: shard3-node-a
    command: mongod --config /etc/mongod.conf --replSet shard3-rs
    volumes:
      - ./mongodb/configs/shardsvr.conf:/etc/mongod.conf:ro
      - ./mongodb/configs/shard3ReplSet.js:/configs/shard3ReplSet.js:ro
      - ./mongodb/scripts/initializingReplSetScript.js:/scripts/initializingReplSetScript.js:ro
      - ./mongodb/scripts/createRootAdmin.js:/scripts/createRootAdmin.js:ro
      - mongodb_cluster_shard3_a_db:/data/db
      - mongodb_cluster_shard3_a_config:/data/configdb
    ports:
      - 27128:27017
    restart: always
    links:
      - shard3-b
      - shard3-c
    networks:
      - ${ENVIRONMENT_NETWORK}
    mem_limit: 200mb

  shard3-b:
    build:
      context: mongodb
    image: mongodb:v8
    container_name: shard3-node-b
    command: mongod --config /etc/mongod.conf --replSet shard3-rs
    volumes:
      - ./mongodb/configs/shardsvr.conf:/etc/mongod.conf:ro
      - mongodb_cluster_shard3_b_db:/data/db
      - mongodb_cluster_shard3_b_config:/data/configdb
    ports:
      - 27129:27017
    restart: always
    networks:
      - ${ENVIRONMENT_NETWORK}
    mem_limit: 200mb

  shard3-c:
    build:
      context: mongodb
    image: mongodb:v8
    container_name: shard3-node-c
    command: mongod --config /etc/mongod.conf --replSet shard3-rs
    volumes:
      - ./mongodb/configs/shardsvr.conf:/etc/mongod.conf:ro
      - mongodb_cluster_shard3_c_db:/data/db
      - mongodb_cluster_shard3_c_config:/data/configdb
    ports:
      - 27130:27017
    restart: always
    networks:
      - ${ENVIRONMENT_NETWORK}
    mem_limit: 200mb

volumes:
  mongodb_cluster_router1_db:
  mongodb_cluster_router1_config:

  mongodb_cluster_router2_db:
  mongodb_cluster_router2_config:

  mongodb_cluster_configsvr1_db:
  mongodb_cluster_configsvr1_config:

  mongodb_cluster_configsvr2_db:
  mongodb_cluster_configsvr2_config:

  mongodb_cluster_configsvr3_db:
  mongodb_cluster_configsvr3_config:

  mongodb_cluster_shard1_a_db:
  mongodb_cluster_shard1_a_config:

  mongodb_cluster_shard1_b_db:
  mongodb_cluster_shard1_b_config:

  mongodb_cluster_shard1_c_db:
  mongodb_cluster_shard1_c_config:

  mongodb_cluster_shard2_a_db:
  mongodb_cluster_shard2_a_config:

  mongodb_cluster_shard2_b_db:
  mongodb_cluster_shard2_b_config:

  mongodb_cluster_shard2_c_db:
  mongodb_cluster_shard2_c_config:

  mongodb_cluster_shard3_a_db:
  mongodb_cluster_shard3_a_config:

  mongodb_cluster_shard3_b_db:
  mongodb_cluster_shard3_b_config:

  mongodb_cluster_shard3_c_db:
  mongodb_cluster_shard3_c_config:
