services:
  primary-db:
    image: mongo
    container_name: primary-db-container
    volumes:
      - ./mongodb/scripts/initializingReplSetScript.js:/scripts/initializingReplSetScript.js
      - ./mongodb/configs/devAndTestReplSetConfig.js:/configs/devAndTestReplSetConfig.js
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "llms-tdm-set" ]

  secondary-db-1:
    image: mongo
    container_name: secondary-db-container-1
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "llms-tdm-set" ]

  secondary-db-2:
    image: mongo
    container_name: secondary-db-container-2
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "llms-tdm-set" ]
