services:
  primary-dev-mongodb:
    image: mongo:8.0.0
    volumes:
      - development-mongodb-data:/data/db
      - ./mongodb/scripts/initializingReplSetScript.js:/scripts/initializingReplSetScript.js
      - ./mongodb/configs/developmentReplSetConfig.js:/configs/developmentReplSetConfig.js
    networks:
      - development-network
    container_name: primary-dev-db
    ports:
      - 27001:27017
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "dev-llms-tdm-set" ]

  secondary-dev-mongodb-1:
    image: mongo:8.0.0
    networks:
      - development-network
    container_name: secondary-dev-db-1
    ports:
      - 27002:27017
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "dev-llms-tdm-set" ]

  secondary-dev-mongodb-2:
    image: mongo:8.0.0
    networks:
      - development-network
    container_name: secondary-dev-db-2
    ports:
      - 27003:27017
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "dev-llms-tdm-set" ]

networks:
  development-network:
    driver: bridge

volumes:
  development-mongodb-data:
