name: Continous Integration Workflow 

on:
  push:
  workflow_dispatch:

jobs:
  run-tests-and-collect-coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Create testing environment variables files
        run: echo "${{ secrets.TESTING_ENV_FILE_CONTENT }}" >> .env.test

      - name: Install dependencies
        run: bun install

      - name: Run tests
        run: bun test --coverage --coverage-reporter=lcov

      - name: Upload code coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage/lcov.info
